###############################################
#                                             #
#   RivalCredits by RivalDevelopment v0.1     #
#                                             #
###############################################
server-id: 'server1'

database:
  # SQLite or MySQL
  database-type: SQLite
  mysql:
    driver: 'com.mysql.jdbc.Driver'
    host: localhost
    port: 3306
    database: dbName
    username: dbUser
    password: dbPassword
permissions:
  admin: rivalcredits.admin
  player: rivalcredits.command
leaderboard:
  # GUI or TEXT
  type: GUI
  text-settings:
    text-places: 10
    text-display:
      - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
      - "&6&lKREDIT TOP"
      - ""
      - "&8&l<&6#&l1&8&l> &e{player-0} &8- &f{value-0} Kredit"
      - "&8&l<&6#&l2&8&l> &e{player-1} &8- &f{value-1} Kredit"
      - "&8&l<&6#&l3&8&l> &e{player-2} &8- &f{value-2} Kredit"
      - "&8&l<&6#&l4&8&l> &e{player-3} &8- &f{value-3} Kredit"
      - "&8&l<&6#&l5&8&l> &e{player-4} &8- &f{value-4} Kredit"
      - "&8&l<&6#&l6&8&l> &e{player-5} &8- &f{value-5} Kredit"
      - "&8&l<&6#&l7&8&l> &e{player-6} &8- &f{value-6} Kredit"
      - "&8&l<&6#&l8&8&l> &e{player-7} &8- &f{value-7} Kredit"
      - "&8&l<&6#&l9&8&l> &e{player-8} &8- &f{value-8} Kredit"
      - "&8&l<&6#&l10&8&l> &e{player-9} &8- &f{value-9} Kredit"
      - "&6Kredit &8┃ &f/credit top"
      - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
  gui-settings:
    gui-name: '&8Kredit toplista'
    gui-size: 54
    gui-slots: [18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34]
    settings:
      next-page:
        slot: 50
        enabled: true
      previous-page:
        slot: 48
        enabled: true
      current-page:
        slot: 49
        enabled: true
    filler:
      enabled: true
      material: 'BLACK_STAINED_GLASS_PANE'
    display-item:
      material: PLAYER_HEAD
      name: '&6&l#{position} &e{player_name}'
      lore:
        - ''
        - '&6▬ &eKredit: &f{value}'
    display-current:
      slot: 13
      enabled: true
      material: PLAYER_HEAD
      name: '&6&l#{position} &e{player_name}'
      lore:
        - ''
        - '&6▬ &eKreditjeid: &f{value}'
    no-display:
      material: PLAYER_HEAD
      base64: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19
      name: '&c&lNincsen játékos'
      lore:
        - ''
        - '&7&o(( Nincsen még játékos. ))'
    no-page:
      material: BARRIER
      name: '&c&lNincsen oldal'
      lore:
        - '&4Mi nem találtuk ezt a oldalt'
        - '&4ez volt a kérve.'
    previous-page:
      material: TIPPED_ARROW
      flags:
        HIDE_ATTRIBUTES: true
        HIDE_POTION_EFFECTS: true
      potion:
        type: INSTANT_HEAL
        extended: false
        upgraded: true
      name: '&c&l<- Előző oldal'
      lore:
        - '&4Kattints hogy lásd a előző oldalt'
    next-page:
      slot: 50
      enabled: true
      material: TIPPED_ARROW
      flags:
        HIDE_ATTRIBUTES: true
        HIDE_POTION_EFFECTS: true
      potion:
        type: LUCK
        extended: false
        upgraded: false
      name: '&a&lKövetkező oldal ->'
      lore:
        - '&2Kattits hogy lásd a kövekező oldalt'
    current-page:
      material: CLOCK
      name: '&e&lOldal %current-page%/%max-pages%'
      lore:
        - '&6Mostani oldal szám'
options:
  pay-offline: false
  update-inventoryname-after-purchase: false # Resets the cursor in some versions
  craftingstore-hook: false
  decimal-format: '#.##'
  use-prefix: false
  main-command: 'credits'
  command-aliases:
    - 'credit'
    - 'coins'
  shop-aliases:
    - 'buy'
    - 'buycraft'
    - 'store'
    - 'coinshop'
placeholders:
  normal: '&f{price} Kredit'
  discount: '&c&m{price-before}&r &a&n{price-after}&r &fKredit &7({percent}%)'
time-placeholders:
  day: 'nap'
  days: 'napok'
  hour: 'óra'
  hours: 'órák'
  minute: 'perc'
  minutes: 'percek'
  second: 'másodperc'
  seconds: 'másodpercek'
special-deals:
  enabled: true
  sync:
    # Enable main-instance: on only 1 server!
    main-instance: false
    time: false
    packages: false
  amount: 2
  shuffle-time: 3600
  packages:
    # category;package;chance;discount
    - 'crates;3;5;5'
    - 'crates;2;50;20'
    - 'crates;1;50;20'
    - 'ranks;1;30;20'
  display:
    # category:slot,slot,slot:timerdisplayslot:page
    - 'main:48,49,50:40:0'
  item:
    material: CLOCK
    name: '&6&lSpeciális ajánlatok'
    lore:
      - '&7Nézd meg a korlátozott időre vonatkozó ajánlatokat alább!'
      - '&7Kérdezd meg, hogy ezek a bolt ajánlatok naponta változnak,'
      - '&7és néhányukkal nem tér vissza, amíg nem változik a bolt ajánlatok,'
      - '&7így használd ki a kedvezményeket, amíg elérhetőek!'
      - ''
      - '&6* &eÚj ajánlatok &f{time-long}'
      - '&e&nNézd meg az ajánlatokat alább.'
  message:
    enabled: true
    message:
      - ''
      - '&6&lKREDIT'
      - ''
      - '&7A kreditek speciális ajánlatokat változnak!'
      - '&7Kérdezd meg, hogy ezek a bolt ajánlatok naponta változnak,'
      - '&7így használd ki a kedvezményeket, amíg elérhetőek!'
      - ''
      - '&7&oKövetkező frissítés &f{next-long}'
most-purchased-package:
  add-lore:
    - ''
    - '&7&o(( &c&lHŐ!, &7csomag vásárolt &f{amount} &7szor))'
  display:
    - "main:53:0"
confirmation-menu:
  options:
    size: 27
    display-item-slot: 13
    display-item-slot-enabled: true
    name: "&8&nBiztos vagy?"
    filler:
      enabled: true
      material: 'STAINED_GLASS_PANE:15'
    confirm:
      slot: 14
      material: LIME_DYE
      name: '&2&l[!] &a&lMegerősítés'
      lore:
        - '&7Kattints a vásárlás megerősítéséhez'
    decline:
      slot: 12
      material: RED_DYE
      name: '&4&l[!] &c&lElutasítás'
      lore:
        - '&7Kattints a vásárlás elutasításához'
        - '&7és vissza.'
discord-webhook:
  purchases:
    enabled: false
    global: true # If true will be active for all packages, if false will be active for only packages with webhook: enabled: true
    webhook-url: ''
    username: 'Rival Credits'
    avatar-url: 'https://i.imgur.com/TwZlgHD.png'
    embed:
      title: 'Új vásárlás'
      content: 'Felhasználó `{player}` vásárolt csomagot `{package}` a kategóriából: `{category}`\n**Vásárlás adatai**:\n Vásárolt idő: {time}\n\nÁr: {price}\nRégi egyenleg: {oldbalance}\nÚj egyenleg: {newbalance}'
      color: (154,205,50)
      footer: 'Rival Credits - {time}'
  #Give Command
  give-command:
    enabled: false
    webhook-url: ''
    username: 'Rival Credits'
    avatar-url: 'https://i.imgur.com/TwZlgHD.png'
    embed:
      title: 'Give parancs végrehajtva'
      content: 'Felhasználó `{receiver}` kapott `{amount}` krediteket `{giver}` által'
      color: GREEN
      footer: 'Rival Credits - {time}'
  #Set Command
  set-command:
    enabled: false
    webhook-url: ''
    username: 'Rival Credits'
    avatar-url: 'https://i.imgur.com/TwZlgHD.png'
    embed:
      title: 'Kredit mennyiség beállítva'
      content: '`{receiver}` krediteket állított be `{amount}`-re `{giver}` által'
      color: GREEN
      footer: 'Rival Credits - {time}'
  #Remove Command
  remove-command:
    enabled: false
    webhook-url: ''
    username: 'Rival Credits'
    avatar-url: 'https://i.imgur.com/TwZlgHD.png'
    embed:
      title: 'Kredit mennyiség eltávolítva'
      content: '`{amount}` krediteket eltávolítottunk `{receiver}`-tól `{remover}` által'
      color: RED
      footer: 'Rival Credits - {time}'
  #Reset Command
  reset-command:
    enabled: false
    webhook-url: ''
    username: 'Rival Credits'
    avatar-url: 'https://i.imgur.com/TwZlgHD.png'
    embed:
      title: 'Kredit mennyiség visszaállítva'
      content: '`{receiver}` krediteket visszaállítottunk `{giver}` által'
      color: RED
      footer: 'Rival Credits - {time}'
  pay-command:
    enabled: false
    webhook-url: ''
    username: 'Rival Credits'
    avatar-url: 'https://i.imgur.com/TwZlgHD.png'
    embed:
      title: 'Játékos fizetett'
      content: '`{player-1}` fizetett `{player-2}`-nek **{amount}** krediteket'
      color: RED
      footer: 'Rival Credits - {time}'






pages:
  no-page:
    material: BARRIER
    name: '&c&lNincs oldal'
    lore:
      - '&4Nem találtuk meg a kért oldalt'
      - '&4amelyet kértél.'
  current-page:
    material: CLOCK
    name: '&e&lOldal %current-page%'
    lore:
      - '&6Mostani oldal szám'
  previous-page:
    material: TIPPED_ARROW
    flags:
      HIDE_ATTRIBUTES: true
      HIDE_POTION_EFFECTS: true
    potion:
      type: INSTANT_HEAL
      extended: false
      upgraded: true
    name: '&c&l<- Előző oldal'
    lore:
      - '&4Kattints hogy lásd a előző oldalt'
  next-page:
    material: TIPPED_ARROW
    flags:
      HIDE_ATTRIBUTES: true
      HIDE_POTION_EFFECTS: true
    potion:
      type: LUCK
      extended: false
      upgraded: false
    name: '&a&lKövetkező oldal ->'
    lore:
      - '&2Kattints hogy lásd a kövekező oldalt'
