# General config for the plugin, wiki for some stuff here https://wiki.discordsrvutils.xyz/
# You should read this topic https://wiki.discordsrvutils.xyz/messages/

# Admins who can use the bot without limits. This can be either user or role IDs.
admins: [1325810002992169010,1104113236904779896, 1325810002954289158]
# Commands that must be disabled, will also hide from help command, Don't use aliases here
disabled-commands: []
# Should We register slash commands into your discord server?
register-slash-commands: true
# Should We register slash commands aliases into your discord server? Setting this to false will reduce the amount of commands shown by this plugin.
register-command-aliases: true
welcomer:
  # Should we do Welcomer?
  enabled: false
  # Channel to send welcomer message, Use ID, No need to change this if dms are enabled
  channel: 0
  # Should we DM the User?
  dm_user: true
  # Welcomer message
  message: 'message:welcome'
  # Role to add when they join the server
  role: 0

goodbye:
  # Should we send goodbye messages?
  enabled: true
  # Channel to send message in, DM unavailable because when they leave there is a big chance of no mutual servers
  channel: 1325810002992169015
  # Message to send
  message: 'Viszlát **[user.asTag]**. Reméljük hamarosan vissza jössz'

# Should we track invites? This enables a whole invite tracking system. https://wiki.discordsrvutils.xyz/invite-tracking
invite-tracking: true
afk:
  # Should we send afk (and no longer afk) messages?
  enabled: true
  # AFK Channel. Leave 0 for default channel for discordsrv
  channel: 1352943841996443688
  # AFK Message
  message: 'message:afk'
  no-longer-afk-message: 'message:no-longer-afk'

# Response of /help command, leave blank to generate. You can use message:msgfile where msgfile is the name of the message file in your messages folder (without json, and you can make a new file)
help-response: ''
# Bungee Mode. This will make bot not respond to commands, and nothing will happen as if plugin not installed (only mc leveling is active). This option should be enabled on all servers except lobby if you use bungee
bungee-mode: false
# Replace errors with small error note. Please note that this is a bad practice. If your console is spammed with errors (by this plugin) Please report at https://discordsrvutils.xyz/support
minimize-errors: false
# Thread Pool Size. Simply, how many tasks the plugin can do as the same time, increase if needed, may use more CPU.
pool-size: 2
# Should we tell you about updates if the updates that remain are dev builds?
dev-updatechecker: true
